# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

#pool: Default
pool: Azure Pipelines
variables:
- group: sonarcloud-properties
  
stages:

# - stage: Build
#   jobs:
#   - job: build
#     displayName: 'Build'
#     steps:
#     - task: Gradle@3
#       inputs:
#         gradleWrapperFile: 'gradlew'
#         tasks: 'build'
#         publishJUnitResults: false
#         javaHomeOption: 'JDKVersion'
#         sonarQubeRunAnalysis: false
#         spotBugsAnalysis: false
#     - task: CmdLine@2
#       inputs:
#        script: ls -l build/libs/spring-boot-kubernetes-0.0.1-SNAPSHOT.jar

#     - publish: $(System.DefaultWorkingDirectory)/build/libs/
#       artifact: Jar

# - stage: Review_SAST
#   dependsOn: Build
  
#   jobs:
#   - job: sonar
#     displayName:  Code Review
#     steps:
#       - task: SonarCloudPrepare@1
#         inputs:
#           SonarCloud: 'sonar-cloud'
#           organization: '$(sonarCloudOrganization)'
#           projectKey: '$(sonarCloudProjectKey)'
#           projectName: '$(sonarCloudProjectName)'
#         displayName: 'Preparing Sonarqube Environment'
    
#       - task: Gradle@3
#         inputs:
#           gradleWrapperFile: 'gradlew'
#           tasks: "sonarqube"
#           javaHomeOption: 'JDKVersion'
#           sonarQubeRunAnalysis: true
#           sqGradlePluginVersionChoice: 'specify'
#           sonarQubeGradlePluginVersion: '3.3'
#         displayName: 'Analyze current Branch'
  
#       - task: SonarCloudPublish@1
#         inputs:
#           pollingTimeoutSec: '300'
#         displayName: 'Publish Analysis Results'
        
#       - task: sonarcloud-buildbreaker@2
#         inputs:
#           SonarCloud: 'sonar-cloud'
#           organization: '$(sonarCloudOrganization)'

- stage: Review_SCA
  #dependsOn: Review_SAST

  jobs:
  - job: sca
    displayName: Review SCA
    steps:
    #  - download: current
    #    artifact: Jar

     - task: Maven@3
       inputs:
         mavenPomFile: 'pom.xml'
         publishJUnitResults: false
         javaHomeOption: 'JDKVersion'
         jdkVersionOption: '1.8'
         mavenVersionOption: 'Default'
         mavenAuthenticateFeed: false
         effectivePomSkip: false
         sonarQubeRunAnalysis: false
      

     - task: dependency-check-build-task@6
       inputs:
         projectName: 'spring-boot-kubernetes'
         scanPath: '$(Pipeline.Workspace)/target/*.jar'
         format: 'HTML'
         failOnCVSS: '10'
         



        